//-------------------------------------------------------------------------------------------------
// Server Index Page for OTA update Apr 2023
//-------------------------------------------------------------------------------------------------

const char* serverIndex =  //indexHtml =
"<body style='font-family: Verdana,sans-serif; font-size: 14px;'>"
"<div style='width:400px;padding:20px;border-radius:10px;border:solid 2px #e0e0e0;margin:auto;margin-top:20px;'>"
"<div style='width:100%;text-align:center;font-size:18px;font-weight:bold;margin-bottom:12px;'>ESP32 firmware update</div>"
"<div style='width:100%;text-align:center;font-size:10px;margin-bottom:12px;'>Version 7. Apr. 2023</div>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload-form' style='width:100%;margin-bottom:8px;'>"
"<input type='file' name='update'>"
"<input type='submit' value='Update' style='float:right;'>"
"</form>"
"<div style='width:100%;background-color:#e0e0e0;border-radius:8px;'>"
"<div id='prg' style='width:0%;background-color:#2196F3;padding:2px;border-radius:8px;color:white;text-align:center;'>0%</div>"
"</div>"
"</div>"
"</body>"
"<script>"
"var prg = document.getElementById('prg');"
"var form = document.getElementById('upload-form');"
"form.addEventListener('submit', e=>{"
"e.preventDefault();"
"var data = new FormData(form);"
"var req = new XMLHttpRequest();"
"req.open('POST', '/update');"
"req.upload.addEventListener('progress', p=>{"
"let w = Math.round((p.loaded / p.total)*100) + '%';"
"if(p.lengthComputable){"
"prg.innerHTML = w;"
"prg.style.width = w;"
"}"
"if(w == '100%') prg.style.backgroundColor = '#04AA6D';"
"});"
"req.send(data);"
"});"
"</script>";

/*
const char* serverIndex =
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"<head>"
"<title>Firmware updater</title>"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0;\" />\r\n""<style>divbox {background-color: lightgrey;width: 200px;border: 5px solid red;padding:10px;margin: 10px;}</style>"
"</head>"
"<body bgcolor=\"#66b3ff\">""<font color=\"#000000\" face=\"VERDANA,ARIAL,HELVETICA\">"
"<h1>ESP firmware update</h1>"
"ver 4.3 - 10. Mai. 2020<br><br>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
"<br>Create a .bin file with Arduino IDE: Sketch -> Export compiled Binary<br>"
"<br><b>select .bin file to upload</b>"
"<br>"
"<br>"
"<input type='file' name='update'>"
"<input type='submit' value='Update'>"
"</form>"
"<div id='prg'>progress: 0%</div>"
"<script>"
"$('form').submit(function(e){"
"e.preventDefault();"
"var form = $('#upload_form')[0];"
"var data = new FormData(form);"
" $.ajax({"
"url: '/update',"
"type: 'POST',"
"data: data,"
"contentType: false,"
"processData:false,"
"xhr: function() {"
"var xhr = new window.XMLHttpRequest();"
"xhr.upload.addEventListener('progress', function(evt) {"
"if (evt.lengthComputable) {"
"var per = evt.loaded / evt.total;"
"$('#prg').html('progress: ' + Math.round(per*100) + '%');"
"}"
"}, false);"
"return xhr;"
"},"
"success:function(d, s) {"
"console.log('success!')"
"},"
"error: function (a, b, c) {"
"}"
"});"
"});"
"</script>";

*/